spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hongweidev/config-repo.git
          username: hwz57751314@qq.com
          password: hw208019
          basedir: C:\Users\msi\Desktop\config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
